name: Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
        exclude: [
            # exclude some windows/macos runners, they run pretty slow
            { platform: windows-latest, python-version: "3.8" },
            { platform: windows-latest, python-version: "3.9" },
            { platform: macos-latest, python-version: "3.8" },
            { platform: macos-latest, python-version: "3.9" },
          ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install packages
        run: |
          python -m pip install --upgrade pip wheel
          pip install '.[testing]'
      - name: Run mypy
        run: |
          mypy --install-types --non-interactive ./sqlite_backup ./tests setup.py
      - name: Run pytest
        run: |
          pytest
      - name: Run flake8
        run: |
          flake8 ./sqlite_backup
